/**
 * Created by willstuckey on 12/3/16.
 */

/**
 *
 */
function createSource_clearNotifications() {
    $('#title_input_feedback').text('');
    if ($('#title_div').hasClass('has-warning')) {
        $('#title_div').removeClass('has-warning');
    }

    $('#location_input_feedback').text('');
    if ($('#location_input').hasClass('has-warning')) {
        $('#location_input').removeClass('has-warning');
    }

    $('#description_input_feedback').text('');
    if ($('#description_input_feedback').hasClass('has-warning')) {
        $('#description_input_feedback').removeClass('has-warning');
    }

    $('#reportid_input').val('autogenerated');
    $('#submitter_input').val(getCookie('username'));
    $('#date_input').val(getCurrentDTFormatted());

    $('#input_feedback').text('');
}

/**
 *
 */
function createSource_init() {
    createSource_clearNotifications();

    $('#create_button').click(function() {
        createSource_clearNotifications();

        var validated = true;
        var title = $('#title_input').val();
        if (!title) {
            validated = false;
            $('#title_input_feedback').text('Title cannot be blank.');
            $('#title_div').addClass('has-warning');
        }

        var location = $('#location_input').val();
        if (!location) {
            validated = false;
            $('#location_input_feedback').text('Location cannot be blank.');
            $('#location_div').addClass('has-warning');
        }

        var type = $('#type_input').val();
        var condition = $('#condition_input').val();
        var date = $('#date_input').val();

        var description = $('#description_input').val();
        if (!description) {
            validated = false;
            $('#description_input_feedback').text('Description cannot be blank.');
            $('#description_div').addClass('has-warning');
        }

        if (validated) {
            var create_data = '';
            create_data += ('email=' + encodeURIComponent(getCookie('email')));
            create_data += ('&tok=' + encodeURIComponent(getCookie('sessionid')));
            create_data += '&reporttype=source';
            create_data += '&action=ADD';
            $.ajax({
                type: "POST",
                url: "api/report.php",
                dataType: "text",
                data: create_data,
                success: function(msg) {
                    var response = parseResponse(msg);
                    if (response['status'] == 'success') {
                        var reportid = response['reportid'];

                        var update_data = '';
                        update_data += 'email=' + encodeURIComponent(getCookie('email'));
                        update_data += '&tok=' + encodeURIComponent(getCookie('sessionid'));
                        update_data += '&reporttype=source';
                        update_data += "&action=UPDATE";

                        update_data += '&reportid=' + encodeURIComponent(reportid);
                        update_data += '&reportdt=' + encodeURIComponent(date);
                        update_data += '&location=' + encodeURIComponent(location);
                        update_data += '&type=' + encodeURIComponent(type);
                        update_data += '&cond=' + encodeURIComponent(condition);
                        update_data += '&name=' + encodeURIComponent(title);
                        update_data += '&description' + encodeURIComponent(description);
                        $.ajax({
                            type: "POST",
                            url: "api/report.php",
                            dataType: "text",
                            data: update_data,
                            success: function(msg) {
                                var response = parseResponse(msg);
                                if (response['status'] == 'success') {
                                    showSuccess('report created (id: ' + reportid + ')');
                                } else {
                                    showError('there was an internal error with data sent to the server');
                                }
                            },
                            error: function(XMLHttpRequest, textStatus, errorThrown) {
                                showError('There was an error communcating with the server.'
                                    + "\n\nXHR Status: " + XMLHttpRequest.status
                                    + "\ntext: " + textStatus
                                    + "\nerror: " + errorThrown);
                            }
                        });
                    } else {
                        showError('there was an internal error with data sent to the server');
                    }
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    showError('There was an error communcating with the server.'
                        + "\n\nXHR Status: " + XMLHttpRequest.status
                        + "\ntext: " + textStatus
                        + "\nerror: " + errorThrown);                }
            });
        } else {
            showInfo('report not submitted');
        }
    });
}