/**
 * Created by willstuckey on 12/3/16.
 */

/**
 *
 */
function createPurity_clearNotifications() {
    $('#location_input_feedback').text('');
    if ($('#location_div').hasClass('has-warning')) {
        $('#location_div').removeClass('has-warning');
    }

    $('#virusppm_input_feedback').text('');
    if ($('#virusppm_div').hasClass('has-warning')) {
        $('#virusppm_div').removeClass('has-warning');
    }

    $('#contaminantppm_input_feedback').text('');
    if ($('#contaminantppm_div').hasClass('has-warning')) {
        $('#contaminantppm_div').removeClass('has-warning');
    }

    $('#reportid_input').val('autogenerated');
    $('#submitter_input').val(getCookie('username'));
    $('#date_input').val(getCurrentDTFormatted());

    $('#input_feedback').text('');
}

/**
 *
 * @param str
 * @returns {boolean}
 */
function validatePPM(str) {
    var test_num = (~~Number(str));
    return ((String(test_num) === str) && (test_num >= 0) && (test_num <= 1e6));
}

/**
 *
 */
function createPurity_init() {
    createPurity_clearNotifications();

    $('#create_button').click(function () {
        createPurity_clearNotifications();

        var validated = true;
        var date = $('#date_input').val();
        var location = $('#location_input').val();
        if (!location) {
            validated = false;
            $('#location_div').addClass('has-warning');
            $('#location_input_feedback').text('Location cannot be empty.');
        }

        var purity = $('#purity_input').val();
        var virusppm = $('#virusppm_input').val();
        if (!virusppm) {
            validated = false;
            $('#virusppm_div').addClass('has-warning');
            $('#virusppm_input_feedback').text('Virus PPM cannot be empty.');
        } else if (!validatePPM(virusppm)) {
            validated = false;
            $('#virusppm_div').addClass('has-warning');
            $('#virusppm_input_feedback').text('Virus PPM must be between 0 and 1000000');
        }

        var contaminantppm = $('#contaminantppm_input').val();
        if (!contaminantppm) {
            validated = false;
            $('#contaminantppm_div').addClass('has-warning');
            $('#contaminantppm_input_feedback').text('Contaminant PPM cannot be empty.');
        } else if (!validatePPM(contaminantppm)) {
            validated = false;
            $('#contaminantppm_div').addClass('has-warning');
            $('#contaminantppm_input_feedback').text('Contaminant PPM must be between 0 and 1000000');
        }

        if (validated) {
            var create_data = '';
            create_data += ('email=' + encodeURIComponent(getCookie('email')));
            create_data += ('&tok=' + encodeURIComponent(getCookie('sessionid')));
            create_data += '&reporttype=purity';
            create_data += '&action=ADD';
            $.ajax({
                type: "POST",
                url: "api/report.php",
                dataType: "text",
                data: create_data,
                success: function(msg) {
                    var response = parseResponse(msg);
                    if (response['status'] == 'success') {
                        var reportid = response['reportid'];

                        var update_data = '';
                        update_data += 'email=' + encodeURIComponent(getCookie('email'));
                        update_data += '&tok=' + encodeURIComponent(getCookie('sessionid'));
                        update_data += '&reporttype=purity';
                        update_data += "&action=UPDATE";

                        update_data += '&reportid=' + encodeURIComponent(reportid);
                        update_data += '&reportdt=' + encodeURIComponent(date);
                        update_data += '&location=' + encodeURIComponent(location);
                        update_data += '&cond=' + encodeURIComponent(purity);
                        update_data += '&virusppm=' + encodeURIComponent(virusppm);
                        update_data += '&contaminantppm=' + encodeURIComponent(contaminantppm);
                        $.ajax({
                            type: "POST",
                            url: "api/report.php",
                            dataType: "text",
                            data: update_data,
                            success: function(msg) {
                                var response = parseResponse(msg);
                                if (response['status'] == 'success') {
                                    showSuccess('report created (id: ' + reportid + ')');
                                } else {
                                    showError('there was an internal error with data sent to the server');
                                }
                            },
                            error: function(XMLHttpRequest, textStatus, errorThrown) {
                                showError('There was an error communcating with the server.'
                                    + "\n\nXHR Status: " + XMLHttpRequest.status
                                    + "\ntext: " + textStatus
                                    + "\nerror: " + errorThrown);
                            }
                        });
                    } else {
                        showError('there was an internal error with data sent to the server');
                    }
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    showError('There was an error communcating with the server.'
                        + "\n\nXHR Status: " + XMLHttpRequest.status
                        + "\ntext: " + textStatus
                        + "\nerror: " + errorThrown);                }
            });
        } else {
            showInfo('report not submitted');
        }

    });
}