<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">

    <!-- Optional theme -->
    <!--<link rel="stylesheet" -->
    <!--href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" -->
    <!--integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" -->
    <!--crossorigin="anonymous">-->

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <script src="js/util/message.js"></script>
    <script src="js/util/cookie.js"></script>
    <script src="js/util/remotes.js"></script>
    <script src="js/util/response.js"></script>
    <script src="js/util/time.js"></script>
    <script src="js/nav.js"></script>
    <script src="js/create_source.js"></script>

    <script type="text/javascript">
        conditionalRedirect();

        function pageInit() {
            nav_setMenuOptions();
            createSource_init();
        }

        $(document).ready(function () {
            pageInit();
        });
    </script>
</head>

<body>
<?php include 'navbar.php' ?>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
            <h1>Create Source Report</h1>

            <div id="message_banner">

            </div>

            <form>
                <div class="form-group" id="reportid_div">
                    <label for="reportid_input">Report ID</label>
                    <input type="text" class="form-control" id="reportid_input" placeholder="autogenerated" disabled>
                    <span id="reportid_input_feedback" class="help-block"></span>
                </div>

                <div class="form-group" id="submitter_div">
                    <label for="submitter_input">Submitter</label>
                    <input type="text" class="form-control" id="submitter_input" placeholder="" disabled>
                    <span id="submitter_input_feedback" class="help-block"></span>
                </div>

                <div class="form-group" id="title_div">
                    <label for="title_input">Title</label>
                    <input type="text" class="form-control" id="title_input" placeholder="">
                    <span id="title_input_feedback" class="help-block"></span>
                </div>

                <div class="form-group" id="location_div">
                    <label for="location_input">Location</label>
                    <textarea class="form-control" id="location_input"></textarea>
                    <span id="location_input_feedback" class="help-block"></span>
                </div>

                <div class="form-group" id="type_div">
                    <label for="type_input">Type</label>
                    <select class="form-control" id="type_input">
                        <option>BOTTLED</option>
                        <option>WELL</option>
                        <option>SPRING</option>
                        <option>LAKE</option>
                        <option>STREAM</option>
                        <option>OTHER</option>
                        <option>UNAVAILABLE</option>
                    </select>
                    <span id="type_input_feedback" class="help-block"></span>
                </div>

                <div class="form-group" id="condition_div">
                    <label for="condition_input">Condition</label>
                    <select class="form-control" id="condition_input">
                        <option>WASTE</option>
                        <option>TREATABLEMUDDY</option>
                        <option>TREATABLECLEAR</option>
                        <option>POTABLE</option>
                        <option>UNAVAILABLE</option>
                    </select>
                </div>

                <div class="form-group" id="date_div">
                    <label for="date_input">Date</label>
                    <input type="text" class="form-control" id="date_input" disabled>
                    <span id="date_input_feedback" class="help-block"></span>
                </div>

                <div class="form_group" id="description_div">
                    <label for="description_input">Description</label>
                    <textarea class="form-control" id="description_input"></textarea>
                    <span id="description_input_feedback" class="help-block"></span>
                </div>

                <div class="form-group">
                    <button type="button" class="btn btn-primary" id="create_button">Create Source Report</button>
                    <span id="input_feedback" class="help-block"></span>
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>